### ISSUE TITLE
Unsupported argument while Terraform init

### ISSUE THREAD

**Issue by ilangrs** [clouddrove/terraform-aws-kms#10]
Hi team,

I am trying to use your KMS module (which is very helpful :)).

After initializing I'm getting the following error:

*******************************************************************************
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported argument

  on .terraform\modules\kms.kms_key\variables.tf line 81, in variable "key_usage":
  81:   sensitive   = true

An argument named "sensitive" is not expected here.

Error: Unsupported argument

  on .terraform\modules\kms.kms_key\variables.tf line 94, in variable "policy":
  94:   sensitive   = true

An argument named "sensitive" is not expected here.

Error: Unsupported argument
***********************************************************************************

this is the code:

`module "kms_key" {
    source      = "clouddrove/kms/aws"
    version     = "0.14.0"
    name        = "x-infra"
    environment = "dev"
    label_order = ["name", "environment"]
    enabled     = true
    description             = "KMS key for X-Infra"
    deletion_window_in_days = 14
    enable_key_rotation     = true
    customer_master_key_spec = "SYMMETRIC_DEFAULT"
    alias                   = "alias/x-infra"
    key_usage               = "ENCRYPT_DECRYPT"
    policy                  = data.aws_iam_policy_document.default.json
}

data "aws_iam_policy_document" "default" {
    version = "2012-10-17"
    statement {
      sid    = "Enable IAM User Permissions"
      effect = "Allow"
      principals {
        type        = "AWS"
        identifiers = ["*"]
      }
      actions   = ["kms:*"]
      resources = ["*"]
    }
}`

To prevent the error I commented out "sensitive   = true" in variable.tf file under .terraform/modules/kms.kms_key/

Am I missing something? Is that a bug?

**Comment by anmolnagpal** [comment]
Hello @ilangrs,

We are checking, will come back to you asap

**Comment by sohanyadav** [comment]
@ilangrs  this is created terraform version 0.14. 0.14 version support the sensitive value, if you deploy with old versions you can run from tags 
Link: https://github.com/clouddrove/terraform-aws-kms/tags

Thanks 

This is not an issue, I'm going to close this ticket
