### ISSUE TITLE
possible to add multi_region

### ISSUE THREAD

**Issue by YarkoGr** [clouddrove/terraform-aws-kms#19]
Hi, is there possible to add multi_region options for yours module, i tried to add in downloaded yours module and it works
![Screenshot from 2022-05-03 20-16-52](https://user-images.githubusercontent.com/50024225/166505190-d553cc0b-a522-4311-8bf1-eb2b108fd1a5.png)

**Comment by sohanyadav** [comment]
@YarkoGr  multi_region added

**Comment by YarkoGr** [comment]
Thanks so much, you are great!

ср, 4 трав. 2022, 19:09 користувач Sohan Yadav ***@***.***>
пише:

**Comment by YarkoGr** [comment]
It's great. Multi-region options is useful in your module
